// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReferenceEngine.Styles.UI.Database;

namespace ReferenceEngine.Styles.UI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200619121503_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("ReferenceEngine.Bibtex.Abstractions.BibliographyStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BibliographyStyles");
                });

            modelBuilder.Entity("ReferenceEngine.Bibtex.Abstractions.EntryStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BibliographyStyleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldsJson")
                        .HasColumnName("Fields")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibliographyStyleId");

                    b.ToTable("EntryStyles");
                });

            modelBuilder.Entity("ReferenceEngine.Bibtex.Abstractions.EntryStyle", b =>
                {
                    b.HasOne("ReferenceEngine.Bibtex.Abstractions.BibliographyStyle", null)
                        .WithMany("EntryStyles")
                        .HasForeignKey("BibliographyStyleId");
                });
#pragma warning restore 612, 618
        }
    }
}
