// <auto-generated />
using System;
using LatexReferences.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LatexReferences.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200518163831_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("LatexReferences.Models.Format.BibliographyStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BibliographyStyles");
                });

            modelBuilder.Entity("LatexReferences.Models.Format.EntryStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BibliographyStyleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BibliographyStyleId");

                    b.ToTable("EntryStyles");
                });

            modelBuilder.Entity("LatexReferences.Models.Format.EntryStyle", b =>
                {
                    b.HasOne("LatexReferences.Models.Format.BibliographyStyle", null)
                        .WithMany("EntryFormats")
                        .HasForeignKey("BibliographyStyleId");
                });
#pragma warning restore 612, 618
        }
    }
}
