// <auto-generated />
using System;
using LatexReferences.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LatexReferences.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("LatexReferences.Models.Format.BibEntryFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FullFormatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeAddress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeAnnote")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeAuthor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeBooktitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeChapter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeCrossReference")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeDOI")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeEdition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeEditor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeHowpublished")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeInstitution")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeJournal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeMonth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeOrganization")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludePages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludePublisher")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSchool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSeries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeTitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeVolume")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullFormatId");

                    b.ToTable("BibEntryFormats");
                });

            modelBuilder.Entity("LatexReferences.Models.Format.FullFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FullFormats");
                });

            modelBuilder.Entity("LatexReferences.Models.Format.BibEntryFormat", b =>
                {
                    b.HasOne("LatexReferences.Models.Format.FullFormat", null)
                        .WithMany("EntryFormats")
                        .HasForeignKey("FullFormatId");
                });
#pragma warning restore 612, 618
        }
    }
}
